### ISSUE TITLE
Exception: Value not ready

### ISSUE THREAD

**Issue by 0xDezzy** [anki/vector-python-sdk#11]
I'm getting a "Value not ready" exception when trying to run any script in the examples. The vector robot is on the same network as my laptop and I can ping it.

The exception is as follows:
```
/opt/vector-python-sdk/examples/apps/interactive_shell# python3 interactive_shell.py 
2018-12-19 08:15:54,179 anki_vector.robot.Robot WARNING  No serial number provided. Automatically selecting XXXXXXXX
2018-12-19 08:15:54,183 anki_vector.connection.Connection INFO     Connecting to 192.168.43.16:443 for Vector-XXXX using /root/.anki_vector/Vector-XXXX-XXXXXXXX.cert
2018-12-19 08:15:54,713 anki_vector.connection.Connection INFO     control_granted_response {
}

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/opt/vector-python-sdk/examples/apps/interactive_shell/interactive_shell.py in <module>
     53     with anki_vector.Robot(args.serial,
     54                            enable_camera_feed=True,
---> 55                            show_viewer=True) as robot:
     56         # Invoke the ipython shell while connected to Vector
     57         ipyshell(usage)

/usr/local/lib/python3.6/dist-packages/anki_vector/robot.py in __enter__(self)
    766 
    767     def __enter__(self):
--> 768         self.connect(self.behavior_activation_timeout)
    769         return self
    770 

/usr/local/lib/python3.6/dist-packages/anki_vector/robot.py in connect(self, timeout)
    727 
    728         # access the pose to prove it has gotten back from the event stream once.
--> 729         while not self.pose:
    730             pass
    731 

/usr/local/lib/python3.6/dist-packages/anki_vector/util.py in wrapped(*args, **kwargs)
    104                 iterations += 1
    105                 if iterations > max_iterations:
--> 106                     raise Exception("Value not ready")
    107                 result = func(*args, **kwargs)
    108             return result

Exception: Value not ready
```

**Comment by msintov** [comment]
Hi @0xDezzy -

Thank you for bringing up this issue. When this occurs, it indicates that the Vector robot unfortunately should be rebooted because the event stream appears to be unreliable. In a future release, our output will be less vague and will instruct the user to reboot. We will also investigate the core internal problem.

Thank you for posting!

- Michelle

**Comment by apockill** [comment]
Hi @msintov I too am running into this problem. I'm trying to run a long-running server that exposes a REST api for controlling the vector, along with a nice webapp interface ([WIP here](https://github.com/apockill/vector-rest-dashboard)). 

I'm really trying to pin down exactly why the stream will become unstable. My symptoms seem to include the vector no longer responding _specifically to camera frame requests_, while still allowing me to move the robot around like usual.

Any ideas for increasing stability?

**Comment by msintov** [comment]
@apockill Regarding a long running camera stream, we are aware of the issue where the stream stops and we are investigating. For the "Value not ready" issue, we are planning a fix internally that should be available in a future release soon. Make sure your app is not connected to the robot at the same time.

**Comment by Neabfi** [comment]
I have the same issue, when I access the camera I have some "Exception: Value not ready” that randomly appear. Still no solution other than reboot Vector?
