### ISSUE TITLE
Remote Control app freeplay mode doesn't work

### ISSUE THREAD

**Issue by krconv** [anki/vector-python-sdk#13]
The freeplay mode in the remote control app attempts to use what I think is an old API for requesting and releasing control of Vector. Because that API is no longer supported, an error is printed whenever the freeplay mode is toggled.

```
TypeError: request_control() got an unexpected keyword argument 'enable'
```

**Comment by msintov** [comment]
@krconv Great catch. We will look into a fix for this.

**Comment by krconv** [comment]
I can submit a PR if at all helpful

**Comment by msintov** [comment]
@krconv We are discussing how best to fix this so we'll take care of it internally, but we do welcome PRs otherwise!

**Comment by krconv** [comment]
Closing this because I don't think it will be able to be addressed
