### ISSUE TITLE
Moving in Reverse

### ISSUE THREAD

**Issue by apockill** [anki/vector-python-sdk#14]
Hi devs,

First off, super super fantastic sdk thus far. It's the cleanest code I get to work with, and I love how absolutely consistent it is across the board. 

Second, I'm working on a side project with the Vector for the next couple of months, and I would love to contribute upstream. It seems like this library is still needing some fleshing out that tends to come from people using it for purposes not originally intended by the authors, so I'd like to be part of the solution.

My first problem I've encountered:
How do I move in reverse? I see a reference to moving in reverse [in the behavior.py](https://github.com/anki/vector-python-sdk/blob/ac12ccb762a232c1afbb170b825189785759abce/anki_vector/behavior.py) motion profile map. I also see it in the protobuf defs. However, it doesn't seem actually usable.

**Proposal 1:**
robot.behavior.drive_straight(
    distance=Distance(distance_mm= **-** 100)
    speed=Speed(speed_mmps=70)
)

**Proposal 2:**
robot.behavior.drive_straight(
    distance=Distance(distance_mm=100)
    speed=Speed(speed_mmps= **-** 70)
)

**Proposal 3:**
robot.behavior.drive_straight(
    distance=Distance(distance_mm=100)
    speed=Speed(speed_mmps=70),
    **reverse=True**
)

My initial thought is that "Proposal 2" would fit best with the paradigm of 'velocity' having to do with direction, but with that in mind, might be confusing to newcomers, in which case reverse=True would be ideal.

Either way, let me know where I can help contribute to the sdk. Cheers!

**Comment by msintov** [comment]
Hi @apockill, thank you for the kind words!

Yes, we welcome contributions so please feel free to open a Pull Request for review.

For an example of driving backwards, take a look at this tutorial:
https://github.com/anki/vector-python-sdk/blob/master/examples/tutorials/08_drive_to_cliff_and_back_up.py

**Comment by apockill** [comment]
Maybe there's something wrong with my vector (or a bug?) but when I try using negative distance, my vector still goes forward :) I figured this was on purpose (some absolute value somewhere?) but if that's supposed to work, then maybe there _is_ a bug.

**Comment by msintov** [comment]
@apockill Could you provide your code that goes forward (maybe it uses negative speed)? Do you see this go backward?

```
import anki_vector
from anki_vector.util import distance_mm, speed_mmps
with anki_vector.Robot(enable_face_detection=True) as robot:
    robot.behavior.drive_straight(distance_mm(-100), speed_mmps(100))
```

**Comment by apockill** [comment]
You are absolutely right- that does work. Maybe my webserver is stripping the sign from my distance somewhere down the line. Thanks!
