### ISSUE TITLE
Vector SDK CancelledError

### ISSUE THREAD

**Issue by pathwayuk** [anki/vector-python-sdk#34]
I'm just starting to learn python (3.8.1) and using the Vector SDK.
Every call I make to anki_vector.Robot produces the same error response.  For instance running the sample 02_drive_square.py exactly as it is.  It works fine - Vector drives in a square.  But always the program seems to crash out on the last command:
Traceback .... 
  robot.behavior.turn_in_place(degrees(90))
....
  File "C:\Program Files (x86)\Python\Python38-32\lib\concurrent\futures\_base.py", line 437, in result
    raise CancelledError()
concurrent.futures._base.CancelledError

I can provide the full code if that would be helpful.
Malcolm

**Comment by stDragon** [comment]
> I'm just starting to learn python (3.8.1) and using the Vector SDK.

3.8 not work, use 3.6.*
I use 3.6.8

**Comment by pathwayuk** [comment]
Thanks stDragon, that worked perfectly!
